[peertube] Extract files also from `streamingPlaylists`
ytdl-org/youtube-dl pull request #26302
Opened 2020-08-11 23:48 UTC by 0l-l0

As mentioned in #26002 some PeerTube instances respond with a seemingly corrupted video descriptor JSON object and the extractor is unable to determine the available file formats in those cases. Turned out that an empty `"files"` array caused those kind of problems but, fortunately, there is an another `"files"` array which can be used instead.

2020-10-03 21:14 UTC, tpikonen commented
This PR indeed fixes #26002. Please merge.

2020-12-30 18:04 UTC, remitamine requested changes

2020-12-30 18:04 UTC, remitamine commented on youtube_dl/extractor/peertube.py
> +        for playlist in video['streamingPlaylists']:
```suggestion
        files = video.get('files') or []
        for playlist in (video.get('streamingPlaylists') or []):
```

2021-01-08 18:43 UTC, 0l-l0 commented
I made an another PR (#27728) because my original repo disappeared after the DMCA take-down.

2021-01-08 18:43 UTC, 0l-l0 commented on youtube_dl/extractor/peertube.py
> +        for playlist in video['streamingPlaylists']:
Corrections in #27728

2021-01-08 18:45 UTC, closed without merging