Alura
ytdl-org/youtube-dl pull request #26464
Opened 2020-08-28 17:53 UTC by hugohaa

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Alura is the biggest tech learning platform in Brazil. 

This PR provides single-video and full-course download methods. It's mandatory to have a valid account to download content.

2020-09-12 03:43 UTC, blackjack4494 commented
added it to my fork 👍

2022-06-06 22:37 UTC, dirkf requested changes
This won't be merged unless someone with an account can test it.

2022-06-06 22:37 UTC, dirkf commented on youtube_dl/extractor/alura.py
> +        {
More maintainable:
```suggestion
        'skip': 'Requires alura account credentials',#
    }, {
```

2022-06-06 22:37 UTC, dirkf commented on youtube_dl/extractor/alura.py
> +        course = self._search_regex(self._VALID_URL, url, 'post url', group='course_name')
```suggestion
        course, video_id = re.match(self._VALID_URL, url).group('course_name', 'id')
```

2023-08-01 00:05 UTC, closed without merging