[ustream] Add video.ibm.com domain
ytdl-org/youtube-dl pull request #26894
Opened 2020-10-15 15:16 UTC by serl

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Looks like this extractor works also with video.ibm.com domain, out of the box, so here I add the domain to the regexes.

Thanks!

2020-10-17 07:08 UTC, aldiskatel approved these changes

2020-10-17 16:00 UTC, dstftw requested changes

2020-10-17 16:00 UTC, dstftw commented on youtube_dl/extractor/ustream.py
> +        },
`only_matching`.

2020-10-17 16:14 UTC, merged

2021-01-15 08:19 UTC, ProgrammerAKL commented
The 'no video formats found' error still occurs with https://video.ibm.com/embed/recorded/129111048
which is the video embedded on the page https://www.visiontv.ca/videos/the-royal-consequences/