[Generic] RSS adding item description
ytdl-org/youtube-dl pull request #27177
Opened 2020-11-24 13:19 UTC by renalid

Add description of RSS feed's items

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
Adding the RSS feed items description if it's available in order to get complete information from the feed.

2020-11-28 21:27 UTC, dstftw requested changes
Add a test.

2020-11-29 19:41 UTC, renalid commented
@dstftw test added. Thanks :-)

2020-11-30 19:23 UTC, dstftw requested changes

2020-11-30 19:23 UTC, dstftw commented on youtube_dl/extractor/generic.py
> +            item_desc = None if item_desc_el is None else item_desc_el.text
Use `xpath_text` instead.

2020-11-30 19:23 UTC, dstftw commented on youtube_dl/extractor/generic.py
> +        },
Just add description check to http://podcastfeeds.nbcnews.com/audio/podcast/MSNBC-MADDOW-NETCAST-M4V.xml test instead.

2020-12-06 15:12 UTC, merged