[Smotri] Remove extractor
ytdl-org/youtube-dl pull request #27358
Opened 2020-12-09 10:27 UTC by mashed-potatoes

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

On July 30, 2018, the _Smotri dot com_ radically changed its direction of activity (it may have been bought out by persons affiliated with Bongacams, a network of erotic video chat sites).
At the moment, the site is a mirror of the Bongacams. Hence there's no point in the extractor, so it should be removed.

2020-12-09 14:58 UTC, dstftw requested changes

2020-12-09 14:58 UTC, dstftw commented on README.md
> -    --video-password PASSWORD        Video password (vimeo, smotri, youku)
This file is autogenerated. Do not edit.

2020-12-09 14:58 UTC, dstftw commented on docs/supportedsites.md
> - - **smotri:user**: Smotri.com user videos
This file is autogenerated. Do not edit.

2020-12-09 18:54 UTC, mashed-potatoes commented
Perhaps I should create a new PR to clean out the commit history.

2020-12-09 19:01 UTC, merged

2020-12-15 08:50 UTC, TeslaLyon commented
Please add support Bongacams.com.

https://github.com/ytdl-org/youtube-dl/issues/27440