try_get larger thumnail images with fallback
ytdl-org/youtube-dl pull request #27503
Opened 2020-12-22 12:16 UTC by ozburo

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [ ] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [ ] Covered the code with tests (note that PRs without tests will be REJECTED)
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

The current RedditRIE extractor simply returns the root thumb url for thumbnails, which is very small. This improvement checks for a larger version and returns that instead.

2020-12-22 13:57 UTC, dstftw commented
Extract all resolutions.

2020-12-22 14:01 UTC, ozburo commented
You mean extract all the available images into a `thumbnails` key and leave the existing `thumbnail` as is? I see what you mean, that would actually be better!

2020-12-22 22:34 UTC, ozburo commented
Yes, much nicer xD

2020-12-26 13:53 UTC, dstftw requested changes
Read coding conventions.

2020-12-26 13:53 UTC, dstftw commented on youtube_dl/extractor/reddit.py
> +            url = url_or_none(unescapeHTML(image['url']))
Breaks.

2020-12-26 13:53 UTC, dstftw commented on youtube_dl/extractor/reddit.py
> +                    'height': int_or_none(image['height']),
Breaks.

2020-12-26 13:53 UTC, dstftw commented on youtube_dl/extractor/reddit.py
> +        for image in images:
Breaks if `...['resolutions']` is not a `list`.

2020-12-26 13:53 UTC, dstftw commented on youtube_dl/extractor/reddit.py
> +    unescapeHTML,
Alphabetic.

2020-12-30 22:14 UTC, closed without merging