[twitch] Switch access token to GraphQL and refactor.
ytdl-org/youtube-dl pull request #27646
Opened 2021-01-03 14:20 UTC by 23rd

### Before submitting a *pull request* make sure you have:
- [ ] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [ ] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

The main purpose of this PR is switching endpoint for the access token from the old `api.twitch.tv/api` to the newest GraphQL.
Looks like the `api.twitch.tv/api` endpoint is still working, but it will be rejected at any time. The `twitch.tv` frontend already uses GraphQL requests to get the access token.

Side changes:
- Removed unused `_download_access_token` method.
- Moved `TwitchGraphQLBaseIE` class to the top after `TwitchBaseIE` class.
- Added a new `_download_base_gql` method to make general GraphQL requests and remove repeated `https://gql.twitch.tv/gql` endpoint strings.

I am open to suggestions for improving the code of this PR.

2021-01-03 15:00 UTC, dstftw requested changes

2021-01-03 15:00 UTC, dstftw commented on youtube_dl/extractor/twitch.py
> +                    playerType: \"site\"
Do not escape quotes inside triple quotes.

2021-01-03 15:28 UTC, 23rd commented on youtube_dl/extractor/twitch.py
> +        channel_id = self._extract_channel_id(access_token['value'], channel_name)
Hmm, okay…

2021-01-05 01:46 UTC, dstftw requested changes

2021-01-05 01:46 UTC, dstftw commented on youtube_dl/extractor/twitch.py
> +            'Downloading access token JSON GraphQL')
Inline.

2021-01-05 01:46 UTC, dstftw commented on youtube_dl/extractor/twitch.py
> +            'Downloading access token JSON GraphQL')
215, 220 DRY.

2021-01-05 01:46 UTC, dstftw commented on youtube_dl/extractor/twitch.py
> +            'Downloading %s access token JSON GraphQL' % video_id)
-`JSON`.

2021-01-05 01:46 UTC, dstftw commented on youtube_dl/extractor/twitch.py
> +            'Downloading access token JSON GraphQL')
-`JSON`.

2021-01-05 19:13 UTC, closed without merging

2021-01-16 04:00 UTC, galipmedia commented
Can anyone here help me? I am trying to hit the endpoint as specified in the code but I am not getting an access token back as the 'value' but rather a json object...
```
  data: {
    videoPlaybackAccessToken: {
      value: '{"authorization":{"forbidden":false,"reason":""},"chansub":{"restricted_bitrates":[]},"device_id":null,"expires":1610841132,"https_required":true,"privileged":false,"user_id":null,"version":2,"vod_id":1234567}',
      signature: '99aecf120103b0bb375bad907aa17a880c51d3c0',
      __typename: 'PlaybackAccessToken'
    }
  },
  extensions: { durationMilliseconds: 70, requestID: '01EW4N4TJSA64ACG62Q2G6KPZM' }
}
```
I am using the same Client-ID that was working with the old api.

2021-01-16 04:26 UTC, TaoziDB commented
'value' you got is a string, the same as 'value' from using old API.

2021-01-16 04:39 UTC, galipmedia commented
Aha thanks @TaoziDB it works, i just had to uri encode it for the next call.