fixed --flat-playlist always showing uploader as none
ytdl-org/youtube-dl pull request #28045
Opened 2021-02-02 07:18 UTC by PrinceOfPuppers

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

running:
```
youtube-dl --flat-playlist -j YOUTUBE_PLAYLIST_URL
```
prior to the bugfix would always have "uploader": none in each playlist item. post fix the proper uploader will appear in said field

2021-02-03 09:05 UTC, adrianheine commented
Hey, thanks for your PR! Please prefix your commit message (and PR title) with `[youtube]` to indicate that it's about the youtube IE.

2021-02-03 09:18 UTC, PrinceOfPuppers commented
> Hey, thanks for your PR! Please prefix your commit message (and PR title) with `[youtube]` to indicate that it's about the youtube IE.

woops sorry, updated.

2021-02-04 02:11 UTC, PrinceOfPuppers commented
got rid of the extra 2 commits i accidentally created when attempting to rename the commit

2021-02-13 22:33 UTC, dstftw requested changes

2021-02-13 22:33 UTC, dstftw commented on youtube_dl/extractor/youtube.py
> -            renderer, lambda x: x['ownerText']['runs'][0]['text'], compat_str)
Do not remove the old pattern.

2021-02-15 18:36 UTC, dstftw commented
Add test.

2021-02-15 20:36 UTC, dstftw requested changes

2021-02-15 20:36 UTC, dstftw commented on test/test_youtube_lists.py
> +                self.assertTrue(entry.get('uploader'))
Test should be added to `_TESTS` of extractor class. Use one of the youtube-dl's test playlists for testing, e.g. https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc.

2021-02-16 22:01 UTC, closed without merging