[utils] Handle user:pass in URLs
ytdl-org/youtube-dl pull request #28801
Opened 2021-04-19 12:59 UTC by hhirtz

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Fixes "nonnumeric port" errors when youtube-dl is given URLs with
usernames and passwords such as:

    http://username:password@example.com/myvideo.mp4

Refs:
- https://en.wikipedia.org/wiki/Basic_access_authentication
- https://tools.ietf.org/html/rfc1738#section-3.1
- https://docs.python.org/3.8/library/urllib.parse.html#urllib.parse.urlsplit

Fixes #18276 (point 4)
Fixes #20258
Fixes #26211 (see comment)

2021-04-20 19:52 UTC, jeanthom commented
LGTM

2021-07-02 14:17 UTC, hhirtz commented
Simplified the code and ticked the "improvement" box instead of the "bug fix" one

2021-07-06 13:24 UTC, hhirtz commented
rebased the branch

2021-07-06 16:35 UTC, jeanthom commented
still LGTM

2021-07-11 19:16 UTC, jeanthom commented
Dear maintainers, please take some time to consider this issue, it finally adds a very important functionality to youtube-dl!

2024-03-03 23:04 UTC, dirkf requested changes
Let's finally add this, but with a structure matching yt-dlp.

2024-03-03 23:20 UTC, dirkf commented on youtube_dl/utils.py
>      return compat_urllib_request.Request(escape_url(sanitize_url(url)), *args, **kwargs)
```suggestion
    url, auth_header = extract_basic_auth(escape_url(sanitize_url(url)))
    if auth_header is not None:
        headers = args[1] if len(args) > 1 else kwargs.get('headers')
        headers = headers or {}
        headers['Authorization'] = auth_header
        if len(args) <= 1 and kwargs.get('headers') is None:
            kwargs['headers'] = headers
            kwargs = compat_kwargs(kwargs)
    return compat_urllib_request.Request(url, *args, **kwargs)
```

2024-03-04 01:20 UTC, dirkf approved these changes

2024-03-04 01:27 UTC, merged