[veejoy] Add new extractor
ytdl-org/youtube-dl pull request #31174
Opened 2022-08-17 00:21 UTC by thilobillerbeck

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [ ] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [ ] Covered the code with tests (note that PRs without tests will be REJECTED)
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This pull request adds support to download videos from https://www.veejoy.de/, a german video site operated and based around the company behind Europa Park. The extractor can be used to download either movies or episodes of series. Since the site seems to be built around nextjs, the extractor searches for `__NEXT_DATA__` and works its way towards the medias metadata and location from there.

Currently the most basic features are supported and the installer defaults to the uncompressed original footage, which surprisingly is lying at a public endpoint in their CDN. A method to extract the compressed chunk-based and compressed video is already in place (`get_video_formats`), but since the CDN seems to use some kind of cookie based checksum verification while downloading, it forbids me to download the chunks via ffmpeg. Unfortunately, I couldn't get my head around the problem yet, but as said, the extractor works with the uncompressed version.

2022-08-17 05:03 UTC, dirkf commented
Please **fully complete the template**. Read all the bold text instructions and set the check boxes accordingly.

2022-08-17 10:12 UTC, thilobillerbeck commented
Well, seems like me being stupid at copying the text I prefilled in another editor. Now it should be complete. 👍

2022-08-17 12:39 UTC, dirkf commented
Finally, as there's no supporting issue, please fill in the [Site support issue template](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=site-support-request&template=2_site_support_request.md) and paste the text into this thread.

2022-08-17 12:46 UTC, dirkf requested changes
Thanks for your work!

I've made some suggestions. Generally, `"string"` -> `'string'`. Maybe the m3u8 downloads can be revived.

2022-08-17 19:09 UTC, thilobillerbeck commented
Thanks for replying to the PR so fast. :) I applied your suggestions and cleaned up some other stuff accordingly. :+1:

2022-08-18 09:07 UTC, thilobillerbeck commented
> Finally, as there's no supporting issue, please fill in the [Site support issue template](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=site-support-request&template=2_site_support_request.md) and paste the text into this thread.

<!--

######################################################################
  WARNING!
  IGNORING THE FOLLOWING TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE
######################################################################

-->


## Checklist

<!--
Carefully read and work through this check list in order to prevent the most common mistakes and misuse of youtube-dl:
- First of, make sure you are using the latest version of youtube-dl. Run `youtube-dl --version` and ensure your version is 2021.12.17. If it's not, see https://yt-dl.org/update on how to update. Issues with outdated version will be REJECTED.
- Make sure that all provided video/audio/playlist URLs (if any) are alive and playable in a browser.
- Make sure that site you are requesting is not dedicated to copyright infringement, see https://yt-dl.org/copyright-infringement. youtube-dl does not support such sites. In order for site support request to be accepted all provided example URLs should not violate any copyrights.
- Search the bugtracker for similar site support requests: http://yt-dl.org/search-issues. DO NOT post duplicates.
- Finally, put x into all relevant boxes (like this [x])
-->

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones


## Example URLs

<!--
Provide all kinds of example URLs support for which should be included. Replace following example URLs by yours.
-->

- Single: https://www.veejoy.de/en/series/o-the-construction-documentary/how-it-all-started
- Single: https://www.veejoy.de/en/movies/making-of-the-secret

## Description

<!--
Provide any additional information.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

See original post.

2022-11-08 19:53 UTC, thilobillerbeck commented on youtube_dl/extractor/veejoy.py
> +        next_data = self._html_search_regex(r'<script id="__NEXT_DATA__" type="application/json">([^<]+)</script>', webpage, 'next_data')
Applied suggestion

2022-11-08 19:56 UTC, thilobillerbeck commented on youtube_dl/extractor/veejoy.py
> +            })
Applied suggestion

2022-11-08 19:57 UTC, thilobillerbeck commented on youtube_dl/extractor/veejoy.py
> +    def get_video_id(self, url):
Applied suggestion

2022-11-08 19:58 UTC, thilobillerbeck commented on youtube_dl/extractor/veejoy.py
> +            return "Veejoy"
Applied suggestion

2022-11-08 19:58 UTC, thilobillerbeck commented on youtube_dl/extractor/veejoy.py
> +        video_data = self.get_video_data(url, video_id)
Applied suggestion

2022-11-08 19:59 UTC, thilobillerbeck commented on youtube_dl/extractor/veejoy.py
> +        final_asset = self.get_original_file_url(video_data, video_id)
Applied suggestion

2022-11-08 20:01 UTC, thilobillerbeck commented on youtube_dl/extractor/veejoy.py
> +            'duration': video_data.get("mediaDuration"),
Added apropriate handlers to each field

2022-11-08 20:03 UTC, thilobillerbeck commented on youtube_dl/extractor/veejoy.py
> +            'url': final_asset.get("contentUrl"),
Applied suggestion

2022-11-08 20:04 UTC, thilobillerbeck commented on youtube_dl/extractor/veejoy.py
> +        asset = self._download_json("https://www.veejoy.de/api/service/get-media-summary?mediaIri=" + self.get_asset_ref(video_data) + "&locale=en", video_id)
Applied suggestion

2022-11-08 20:05 UTC, thilobillerbeck commented on youtube_dl/extractor/veejoy.py
> +            if asset_format["mimeType"] == "video/mp4":
Applied suggestion

2022-11-08 20:06 UTC, thilobillerbeck commented on youtube_dl/extractor/veejoy.py
> +            if mediaAsset["type"] == "SOURCE":
Applied suggestion

2022-11-08 20:06 UTC, thilobillerbeck commented on youtube_dl/extractor/extractors.py
> +from .veejoy import VeejoyIE
Applied suggestion

2022-11-08 20:20 UTC, thilobillerbeck commented on youtube_dl/extractor/veejoy.py
> +                })
Applied suggestions

2022-11-08 20:21 UTC, thilobillerbeck commented
Hi, I finally managed to go through all your suggestions and chek against what I've applied.

2022-11-10 16:20 UTC, dirkf commented on youtube_dl/extractor/veejoy.py
> +            if transcodingFormat == {}:
```suggestion
            transcodingFormat = try_get(asset_format, lambda x: x['transcodingFormat'], dict)

            if not transcodingFormat:
```

2022-11-10 16:23 UTC, dirkf commented on youtube_dl/extractor/veejoy.py
> +    ExtractorError,
```suggestion
```

2024-01-30 23:17 UTC, closed without merging