[americastestkitchen] Add support for downloading entire series
ytdl-org/youtube-dl pull request #31493
Opened 2023-01-25 05:27 UTC by bm1549

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

This PR adds the ability to download entire series of ATK as youtube-dl playlists.

2023-01-25 05:29 UTC, lilykuong approved these changes

2023-01-25 14:04 UTC, dirkf commented on youtube_dl/extractor/americastestkitchen.py
> +    _VALID_URL = r'https?:\/\/(?:www\.)?(?P<show>americastestkitchen|cookscountry)\.com\/?(episodes\/browse\/season_(?P<season>\d+))?'
```suggestion
    _VALID_URL = r'https?://(?:www\.)?(?P<show>americastestkitchen|cookscountry)\.com(?:/(?:episodes/browse/season_(?P<season>\d+))?)?'
```

2023-01-25 17:06 UTC, dirkf requested changes
Thanks for your work!

I made a few suggestions but, good news, I wanted to test them and ended up with the attached [americastestkitchen.py](https://github.com/ytdl-org/youtube-dl/files/10501697/americastestkitchen.py.txt) that passes all the old and new tests and pulls in anything useful that yt-dlp had added. By all means, if you're happy with my version, commit it into your branch instead of responding to the suggestions.

2023-01-25 17:06 UTC, dirkf commented on youtube_dl/extractor/americastestkitchen.py
> +            facet_filters.append('search_atk_episode_season:' + season)
I had to use this:
```suggestion
            facet_filters.append('search_season_list:' + season)
```

2023-01-25 17:06 UTC, dirkf commented on youtube_dl/extractor/americastestkitchen.py
> +        playlist_id, playlist_title = ('season_%d' % season_number, 'Season %d' % season_number) if season_number else (show, title)
Could merge this with the conditional block at l.145.

2023-01-26 13:19 UTC, dirkf commented on youtube_dl/extractor/americastestkitchen.py
> +            playlist_title, headers={
Prompted by your variable rename, I realised that this parameter is meant to be an ID. Let's use that instead.
```suggestion
            playlist_id, headers={
```

2023-01-26 13:20 UTC, dirkf approved these changes
I made a small update and otherwise good to go, thanks.

2023-01-28 18:52 UTC, bm1549 commented
@dirkf could you merge this in for me? I don't have the permissions to do it

2023-02-02 16:58 UTC, merged