[feat]: Add support to external downloader aria2p
ytdl-org/youtube-dl pull request #31500
Opened 2023-01-27 11:40 UTC by teddy171

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

This pull request support a external downloader aria2p(a command-line tool and Python library to interact with an aria2c daemon process through JSON-RPC). It can make download faster and get the rate of progress and other information such as download speed, eta time more easily(compared with use aria2c only). When use aria2p, install aria2c and aria2p(by pip) first. **Run aria2c and enable with the --enable-rpc option in the background.** Then all data will download with the aria2c daemon process.

For example:
```bash
python -m youtube_dl --external-downloader aria2p "http://www.youtube.com/watch?&v=BaW_jenozKc"
```

2023-01-27 15:19 UTC, dirkf requested changes
Thanks for this interesting proposal.

Although (currently) it would only be useful with Python versions that are supported for _aria2fp_, I'd be happy to incorporate it as long as there are no unwanted side-effects when it's not available or supported.

Supposing someone has yt-dl installed with Python 2.7 but also has _aria2fp_ installed with a supported Python3, there could be an option to invoke _aria2fp_ by its CLI. I guess that would best be addressed with two FD classes, perhaps with some inheritance.

I've made some detailed suggestions to consider. Let me know what you think.

2023-01-28 00:36 UTC, dirkf reviewed
Somehow you've missed my existing review.

2023-01-28 06:38 UTC, teddy171 commented on youtube_dl/downloader/external.py
> +        while download.status == "active":
```download``` do have a ```.status```. But its value could be ```waiting```, but when I test it, it seem return ```active``` immediately. Should I add ```waiting``` to the check?

2023-01-28 09:01 UTC, teddy171 commented
I think there is some problems. It raise ```AttributeError: 'Aria2pFD' object has no attribute '_filename'``` in line 256 external.py. Should I use the function ```undo_temp_name``` which in ```FileDownloader```?

2023-01-28 13:11 UTC, dirkf commented on youtube_dl/downloader/external.py
> +            'filename': self._filename,
```suggestion
            'filename': self.__filename,
```

2023-01-28 13:16 UTC, dirkf commented on youtube_dl/downloader/external.py
> +        while download.status == "active":
I think you should handle all the documented statuses that might be returned. I could see `waiting` in your animation.

If there's no documentation in the _aria2p_ project (or in the JSON-RPC spec for aria2), look under the hood of the _aria2p_ code to see what might appear.

I guess there will be `complete` that breaks the polling loop, plus some good values (`active`, `waiting`, ...?) that will continue the loop and anything else will be an error that breaks the loop.

2023-01-28 13:17 UTC, dirkf commented on youtube_dl/downloader/external.py
> +            'filename': self._filename,
That was the problem

2023-01-28 13:30 UTC, dirkf commented
If you apply all the suggestions, and now that I've fixed the bad one, the CI tests might pass. Install _flake8_ with _pip_ and run _flake8_ on your code to identify code issues that will fail the Linter step (unused variables, indentation, etc).

You could make up a test harness like `youtube-dl/test/test_downloader_http.py` to check that your code actually works. The CI tests will only show that it doesn't break other things.

2023-01-30 01:05 UTC, teddy171 commented on youtube_dl/downloader/external.py
> +            'filename': self._filename,
```
AttributeError: 'Aria2pFD' object has no attribute '_Aria2pFD__filename'
```
Seem it still cannot work.

2023-01-30 01:36 UTC, dirkf commented on youtube_dl/downloader/external.py
> +    except ModuleNotFoundError:
```suggestion
    except ImportError:
```

2023-01-30 10:42 UTC, rautamiekka commented
Surely using PyCharm, being a very powerful dedicated Python IDE, would help a lot.

2023-01-30 11:41 UTC, dirkf commented
A test harness can be committed into the repository and used to test regressions (though in this case it would have to be disabled from the automatic CI tests).

2023-02-03 13:46 UTC, teddy171 commented
Is it OK to merge?

2023-02-06 22:06 UTC, dirkf commented
Make your test succeed trivially if the aria2p package isn't available, but run fully if it is. Post the successful test log from your environment.

2023-02-07 09:39 UTC, teddy171 commented
My test log
```bash
$ python -m unittest test/test_external_downloader.py 
..
----------------------------------------------------------------------
Ran 2 tests in 0.667s

OK
```
Is it OK?

2023-02-07 11:49 UTC, dirkf requested changes
Almost ready to go, I hope.

2023-02-07 11:49 UTC, dirkf commented on test/test_external_downloader.py
> +            pass
Don't we want know if this failed?
```suggestion
```

2023-02-07 11:49 UTC, dirkf commented on test/test_external_downloader.py
> +            mobj = re.search(r'^bytes=(\d+)-(\d+)', range_header)
```suggestion
            mobj = re.match(r'bytes=(\d+)-(\d+)', range_header)
```

2023-02-07 11:49 UTC, dirkf commented on test/test_external_downloader.py
> +                end = int(mobj.group(2))
```suggestion
                start, end = (int(mobj.group(i)) for i in (1, 2))
```

2023-02-07 11:49 UTC, dirkf commented on test/test_external_downloader.py
> +            assert False
```suggestion
            assert False, 'unrecognised server path'
```

2023-02-07 11:49 UTC, dirkf commented on test/test_external_downloader.py
> +class TestAria2pFD(unittest.TestCase):
Automate skipping, which will document whether the test ran fully:
```suggestion
@unittest.skipUnless(Aria2pFD.available(), 'aria2p module not found')
class TestAria2pFD(unittest.TestCase):
```

2023-02-07 11:49 UTC, dirkf commented on youtube_dl/downloader/external.py
> +        aria2 = aria2p.API(
The `aria2p` module namespace was already imported:
```suggestion
        aria2 = self.aria2p.API(
```

2023-02-07 11:49 UTC, dirkf commented on youtube_dl/downloader/external.py
> +        options["header"] = []
Use `'`: project convention.

2023-02-08 13:42 UTC, teddy171 commented
Thank you for your suggestions @dirkf. I have applied your suggestions. Is it able to merge now?

2023-02-09 11:14 UTC, dirkf reviewed
I'll just apply some Lint, style and simplification fixes. If the CI tests work, please post your test output too. If all good we can merge.

2023-02-09 11:14 UTC, dirkf commented on test/helper.py
```suggestion


```

2023-02-09 11:14 UTC, dirkf commented on test/helper.py
```suggestion


```

2023-02-09 11:14 UTC, dirkf commented on test/test_downloader_http.py
> +from test.helper import FakeLogger, http_server_port, try_rm
```suggestion
from test.helper import (
    FakeLogger,
    http_server_port,
    try_rm,
)
```

2023-02-09 11:14 UTC, dirkf commented on test/test_external_downloader.py
> +from test.helper import FakeLogger, http_server_port, try_rm
```suggestion
from test.helper import (
    FakeLogger,
    http_server_port,
    try_rm,
)
```

2023-02-09 11:14 UTC, dirkf commented on test/test_http.py
> +from test.helper import http_server_port, FakeLogger
```suggestion
from test.helper import (
    FakeLogger,
    http_server_port,
)
```

2023-02-09 11:14 UTC, dirkf commented on youtube_dl/downloader/external.py
> +            options['dir'] = os.path.abspath('.')
```suggestion
        options['dir'] = os.path.dirname(tmpfilename) or os.path.abspath('.')
```

2023-02-09 11:14 UTC, dirkf commented on youtube_dl/downloader/external.py
> +        return not download.status == 'complete'
```suggestion
        return download.status != 'complete'
```

2023-02-09 11:14 UTC, dirkf commented on test/test_external_downloader.py
> +
```suggestion


```

2023-02-09 13:04 UTC, teddy171 commented
The new code is OK. Thank you @dirkf. Test Log
```bash
$ python -m unittest test/test_external_downloader.py 
..
----------------------------------------------------------------------
Ran 2 tests in 0.586s

OK
```

2023-02-09 20:09 UTC, dirkf approved these changes

2023-02-09 20:11 UTC, dirkf commented
And in the CI tests, as expected:
```
test_chunked (test.test_external_downloader.TestAria2pFD) ... SKIP: aria2p module not found
test_regular (test.test_external_downloader.TestAria2pFD) ... SKIP: aria2p module not found
```
On reflection the test file ought to be named like the one for HTTP, so I did that.

2023-02-09 20:19 UTC, merged