[KommunetvIE] Add extractor for kommunetv.no
ytdl-org/youtube-dl pull request #31516
Opened 2023-02-06 12:03 UTC by fonkap

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
Adds support for kommunetv.no

Fixes:

https://github.com/ytdl-org/youtube-dl/issues/30801

2023-02-06 12:23 UTC, fonkap commented
This extractor only downloads the first camera. I don't know a proper way to handle multiple cams.

2023-02-09 13:01 UTC, dirkf requested changes
Thanks for your work!

Just a few nits. Then check the CI tests and should be OK to merge.

2023-02-09 16:14 UTC, fonkap commented on youtube_dl/extractor/kommunetv.py
> +        url = self._search_regex(r'(^[^\?]*)', file, 'url')
nice!

2023-02-09 16:23 UTC, fonkap commented on youtube_dl/extractor/kommunetv.py
> +        url = self._search_regex(r'(^[^\?]*)', file, 'url')
oops there is a problem with this.
base_url removes the filename

2023-02-09 17:11 UTC, fonkap commented
sorry, wrong commit msg, should be:
[KommunetvIE] revert base_url to regex

2023-02-09 17:13 UTC, fonkap reviewed
base_url drops the filename before the ? in the url

2023-02-09 23:31 UTC, dirkf commented on youtube_dl/extractor/kommunetv.py
> +        url = self._search_regex(r'(^[^\?]*)', file, 'url')
What does the `file` look like?

2023-02-09 23:32 UTC, dirkf commented
> sorry, wrong commit msg, should be: [KommunetvIE] revert base_url to regex

We'll squash the commits in the merge anyway, but feel free to rebase and push again.

2023-02-09 23:39 UTC, dirkf commented on youtube_dl/extractor/kommunetv.py
> +        url = self._search_regex(r'(^[^\?]*)', file, 'url')
Oh, yes, I should know (#31490), sorry.

As of today try this instead (you may need to sync from the latest master):
`url = update_url(file, query=None, fragment=None)`

2023-02-10 07:36 UTC, fonkap reviewed
Using update_url.
Works fine, thank you very much!

2023-02-11 02:46 UTC, dirkf approved these changes

2023-02-11 02:47 UTC, merged