[NhkVod] Fix: NhkVod Extractor  / [Piksel] Feat: Add variable host support
ytdl-org/youtube-dl pull request #32213
Opened 2023-05-19 19:08 UTC by menschel

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [NA] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

NHK World VOD is broken since a few weeks.

This is due changing to self-hosted API and player instance.

Necessary tweaks were to
- make PikselIE use the host of the given URL instead of hard-coded Piksel host.
- use the correct template url for the initial API call in NhkVodIE

2023-05-19 19:10 UTC, menschel commented
Honestly, I hope this does not result in nitpicking again!
Take it or drop it.

2023-05-26 11:28 UTC, dirkf commented
>... again ??

2023-05-26 11:46 UTC, dirkf requested changes
Thanks for your work!

Looks good: I've made some small suggestions for project conventions and robustness.

2023-05-26 11:46 UTC, dirkf commented on youtube_dl/extractor/nhk.py
> +
```suggestion
```

2023-05-26 11:46 UTC, dirkf commented on youtube_dl/extractor/piksel.py
> +    urljoin
```suggestion
    urljoin,
```

2023-05-26 11:46 UTC, dirkf commented on youtube_dl/extractor/piksel.py
> +    def _call_api(self, app_token, resource, display_id, query, host="https://player.piksel.com", fatal=True):
```suggestion
    def _call_api(self, app_token, resource, display_id, query, host='https://player.piksel.com', fatal=True):
```

2023-05-26 11:46 UTC, dirkf commented on youtube_dl/extractor/piksel.py
> +        response = (self._download_json(url, display_id, query=query, fatal=fatal) or {}).get('response')
We could ensure that a `dict` is always returned, even if the returned JSON isn't one (add `traverse_obj` to utils imports). Also, no need to use kwargs for `urljoin()`:
```suggestion
        url = urljoin(host, '/ws/ws_%s/api/%s/mode/json/apiv/5' % (resource, app_token))
        response = self._download_json(url, display_id, query=query, fatal=fatal)
        response = traverse_obj(response, 'response', expected_type=dict) or {}
```

2023-05-26 15:09 UTC, menschel reviewed
Accepted changes.

2023-05-26 21:59 UTC, dirkf commented on youtube_dl/extractor/piksel.py
>      try_get,
```suggestion
    traverse_obj,
    try_get,
```

2023-05-29 09:40 UTC, menschel commented on youtube_dl/extractor/piksel.py
> +    traverse_obj,
This is now duplicate ?!

2023-05-29 10:13 UTC, menschel commented
To say it bluntly, this code review process did not yield any significant quality improvement.
It merely wasted 1 week and introduced a flake8 issue along the way.
Solving this simple duplicate import made me realize how Github has slided down in Quality after Micro$oft has taken over Regime. Please move to another platform.

2024-05-26 07:01 UTC, closed without merging