👷 use latest major version for actions/checkout
ytdl-org/youtube-dl pull request #32672
Opened 2023-12-22 13:35 UTC by thomasmerz

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Use latest major version of [actions/checkout](https://github.com/actions/checkout) for GitHub Actions.

2024-01-13 00:54 UTC, dirkf commented
What would be useful is to go through the CI here, and in the dependent actions repos here, and in the nightly repo (separate PRs, obvs) changing all uses to v4 **and setting `progress: false` in the `with` parameter list (see the action changelog and PR 1067 describing this). If you, or anyone, does do so, pls announce any new PRs from the other repos here.

2024-06-05 14:32 UTC, thomasmerz commented
Hey @dirkf , are you interested in my PR or should I close it? Can I help in anyway with your CI or what will be done…? 🤔

2024-06-05 15:15 UTC, dirkf commented
I just love the pointless version dependency hell that is the GH actions ecosystem.

Apparently changing to v4 might clear some warnings about node.js versions. Why that needs new major version is far from clear. But we do get the new `--show-progress` option that we should set, as above. Instead we could set version `master`, or whatever syntax, if it exists, that means `v4` or later (is this field actually a git commit-ish ?)

Then we need to make the equivalent changes in the [nightly](https://github.com/ytdl-org/ytdl-nightly) repo.

2024-06-05 15:27 UTC, dirkf requested changes
What do you think?

2024-06-05 15:27 UTC, dirkf commented on .github/workflows/ci.yml
> +      uses: actions/checkout@v4
1. Avoid having to change the version again (maybe?).
2. Inhibit checkout progress spam.
```suggestion
      uses: actions/checkout@master
      with:
        show-progress: false
```

2024-06-05 15:27 UTC, dirkf commented on .github/workflows/ci.yml
> +    - uses: actions/checkout@v4
```suggestion
      uses: actions/checkout@master
      with:
        show-progress: false
```

2024-06-11 21:46 UTC, dirkf commented on .github/workflows/ci.yml
> +      uses: actions/checkout@master
```suggestion
      # v4+ of the action respect show-progress
      uses: actions/checkout@master
```

2024-06-11 22:12 UTC, dirkf commented on .github/workflows/ci.yml
> +      uses: actions/checkout@master
```suggestion
    - name: Checkout
      uses: actions/checkout@master
```

2024-06-12 00:06 UTC, dirkf commented
That looks better! But I'm still undecided whether it's appropriate to use `@v4`, `@master`, or no version.

To expand on https://github.com/ytdl-org/youtube-dl/pull/32672#issuecomment-2150330366, in principle it should be enough to use `@v4`. However the action devs don't maintain a `v4` interface. Instead if they want to use a new version of, say, Node (an internal change that should not affect action functionality) they make the change in the latest release only, so propagating their technical debt to all users of the action. Those users then have to update the action version even if they are not using any new features of the action.

2025-04-09 15:02 UTC, thomasmerz commented
Hey @dirkf , are you still undecided about this? I'm looking forward to close my PR if it's of no use to this project… Please give feedback if I can close or if you want some changes.

2025-07-08 16:46 UTC, closed without merging