[extractor/safari] Fix extractor
ytdl-org/youtube-dl pull request #32812
Opened 2024-06-12 09:24 UTC by D357R0Y3R

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [ ] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [ ] Covered the code with tests (note that PRs without tests will be REJECTED)
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Hey @dirkf, @epsilonSpider, @Kerruba I just tried to modify this code a bit with updated urls to fix the downloading at least but still getting 1 minute video download error. Seems like kaltura extractor is having problem downloading correct index.m3u8.

2024-06-12 09:57 UTC, dirkf commented
Is there an issue that should be linked? Otherwise you could post a failing verbose log (using the master or nightly code).

2024-06-12 15:51 UTC, D357R0Y3R commented
Sometimes I am getting kaltura extractor error after downloading first video which is also defaulting to the 1:00 minute.

BTW I am sharing the verbose logs

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', 'https://learning.oreilly.com/course/python-complete/9781835465141', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.9.3-zen1-1-zen-x86_64-with-glibc2.39 - OpenSSL 3.3.1 4 Jun 2024 - glibc 2.39
[debug] exe versions: ffmpeg 6.1.1, ffprobe 6.1.1
[debug] Proxy map: {}
[generic] 9781835465141: Requesting header
[redirect] Following redirect to https://www.oreilly.com/videos/python-complete/9781835465141/
[safari:course] 9781835465141: Downloading course JSON
[download] Downloading playlist: Python – Complete Python, Django, Data Science and ML Guide
[safari:course] playlist Python – Complete Python, Django, Data Science and ML Guide: Collected 470 video ids (downloading 470 of them)
[download] Downloading video 1 of 470
[safari:api] 9781835465141/video1_1: Downloading part JSON
[Kaltura] 9781835465141-video1_1: Downloading webpage
[Kaltura] 1_4kzn6p7b: Downloading video info JSON
[Kaltura] 1_4kzn6p7b: Checking mp4-1829 URL
[Kaltura] 1_4kzn6p7b: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/1_4kzn6p7b/format/url/protocol/http/flavorId/1_lmo6gks3'
[download] Destination: Introduction to the Complete Python Guide-1_4kzn6p7b.mp4
[download] 100% of 17.36MiB in 00:30
[download] Downloading video 2 of 470
[safari:api] 9781835465141/video1_2: Downloading part JSON
[Kaltura] 9781835465141-video1_2: Downloading webpage
[Kaltura] 1_6w8js3cg: Downloading video info JSON
[Kaltura] 1_6w8js3cg: Checking mp4-656 URL
[Kaltura] 1_6w8js3cg: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/1_6w8js3cg/format/url/protocol/http/flavorId/1_h93c65eo'
[download] Destination: Course Overview-1_6w8js3cg.mp4
[download] 100% of 5.00MiB in 00:09
[download] Downloading video 3 of 470
[safari:api] 9781835465141/video1_3: Downloading part JSON
[Kaltura] 9781835465141-video1_3: Downloading webpage
[Kaltura] 1_shb1bbeq: Downloading video info JSON
[Kaltura] 1_shb1bbeq: Checking mp4-517 URL
[Kaltura] 1_shb1bbeq: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/1_shb1bbeq/format/url/protocol/http/flavorId/1_9fkfiea4'
[download] Destination: Where to Write and Run Python Code-1_shb1bbeq.mp4
[download] 100% of 6.04MiB in 00:11
[download] Downloading video 4 of 470
[safari:api] 9781835465141/video1_4: Downloading part JSON
[Kaltura] 9781835465141-video1_4: Downloading webpage
[Kaltura] 1_n5y3sn9d: Downloading video info JSON
[Kaltura] 1_n5y3sn9d: Checking mp4-595 URL
```

2024-06-12 15:59 UTC, D357R0Y3R commented
I have again tried to simplify the extractor and updated it. Please check that out

2024-06-12 18:44 UTC, dirkf commented
Also, see https://github.com/yt-dlp/yt-dlp/issues/3526#issuecomment-2129882177.

2024-06-12 19:14 UTC, D357R0Y3R commented
> Probably the free version is what was analyzed. For an entire course, your API URL can be fetched with `_download_json()` and the playlist extracted. Tyhe playlist items like https://learning.oreilly.com/api/v1/book/9781835465141/chapter/video1_2.html also give JSON (despite appearances) and then you have a block like this for each video clip:
> 
> ```python
>     {
>       'thumbnail': null,
>       'reference_id': '9781835465141-video1_2',
>       'brightcove_id': null,
>       'video_still': null,
>       'created_time': null,
>       'last_modified_time': null,
>       'duration_seconds': 346,
>       'streaming_source': 'Kaltura'
>     }
> ```
> 
> This was served to me in a non-JS browser with no authentication.
> 
> IIRC Kaltura needs the video ID (or ref_id, as here, I guess) and partner/account IDs, which are probably effectively constant but should be found in the page or linked JS code. From the clip parameters one might infer that some clips are hosted at Brightcove, so it would be good to find a case where that applies.

Nope I am not using any free version. I have also tried to create an trial account today and tried to watch the full video using that but the extractor maybe only trying to fetch kaltura link wrongly so that the full duration file is not properly fetched. I already fixed the

> Also, see [yt-dlp/yt-dlp#3526 (comment)](https://github.com/yt-dlp/yt-dlp/issues/3526#issuecomment-2129882177).

I have actually fixed the KeyError('next') bug using this pull request already. The problem is its fetching the kaltura demo link off the video instead of the full video length. Oreilly changed something to their API so its no more working. Actually I was using it for a long time to download playlists. But its no more working to download the playlist with full video length.

2024-06-12 19:31 UTC, D357R0Y3R commented
> Also, see [yt-dlp/yt-dlp#3526 (comment)](https://github.com/yt-dlp/yt-dlp/issues/3526#issuecomment-2129882177).

Tried to patch this file same results as me. Limiting downloading to 1:00 minute

2024-06-12 20:48 UTC, D357R0Y3R commented
Got another interesting problem where it really downloads the wrong format even if I set the --format mp4-2363 for an example in the flag it always downloads the format mp4-1829 with less file size than the original one.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.oreilly.com/library/view/python-complete/9781835465141', '--playlist-items', '1', '--list-formats', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.9.3-zen1-1-zen-x86_64-with-glibc2.39 - OpenSSL 3.3.1 4 Jun 2024 - glibc 2.39
[debug] exe versions: ffmpeg 6.1.1, ffprobe 6.1.1
[debug] Proxy map: {}
[safari:course] 9781835465141: Downloading course JSON
[download] Downloading playlist: Python – Complete Python, Django, Data Science and ML Guide
[safari:course] playlist Python – Complete Python, Django, Data Science and ML Guide: Collected 470 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[safari:api] 9781835465141/video1_1: Downloading part JSON
[Kaltura] 9781835465141-video1_1: Downloading webpage
[Kaltura] 1_4kzn6p7b: Downloading video info JSON
[Kaltura] 1_4kzn6p7b: Checking mp4-1829 URL
[Kaltura] 1_4kzn6p7b: Downloading m3u8 information
[info] Available formats for 1_4kzn6p7b:
format code  extension  resolution note
mp4-56       mp4        audio only   56k , isom container, 0fps, ~1.04MiB
hls-58       mp4        audio only   58k , mp4a.40.2
mp4-464      mp4        640x360     464k , isom container, avc1, 30fps, ~8.60MiB
hls-508      mp4        640x360     508k 
mp4-660      mp4        854x480     660k , isom container, avc1, 30fps, ~12.22MiB
hls-713      mp4        854x480     713k 
mp4-827      mp4        960x540     827k , isom container, avc1, 30fps, ~15.32MiB
hls-887      mp4        960x540     887k 
mp4-1272     mp4        1280x720   1272k , isom container, avc1, 30fps, ~23.55MiB
hls-1353     mp4        1280x720   1353k 
mp4-1356     mp4        1280x720   1356k , isom container, avc1, 30fps, ~25.11MiB
mp4-1829     mp4        1920x1080  1829k , m4v container, avc1, 60fps, ~33.85MiB
mp4-2363     mp4        1920x1080  2363k , isom container, avc1, 30fps, ~43.74MiB (best)
[download] Finished downloading playlist: Python – Complete Python, Django, Data Science and ML Guide
```
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.oreilly.com/library/view/python-complete/9781835465141', '--playlist-items', '1', '--format', 'mp4-2363', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.9.3-zen1-1-zen-x86_64-with-glibc2.39 - OpenSSL 3.3.1 4 Jun 2024 - glibc 2.39
[debug] exe versions: ffmpeg 6.1.1, ffprobe 6.1.1
[debug] Proxy map: {}
[safari:course] 9781835465141: Downloading course JSON
[download] Downloading playlist: Python – Complete Python, Django, Data Science and ML Guide
[safari:course] playlist Python – Complete Python, Django, Data Science and ML Guide: Collected 470 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[safari:api] 9781835465141/video1_1: Downloading part JSON
[Kaltura] 9781835465141-video1_1: Downloading webpage
[Kaltura] 1_4kzn6p7b: Downloading video info JSON
[Kaltura] 1_4kzn6p7b: Checking mp4-1829 URL
[Kaltura] 1_4kzn6p7b: Downloading m3u8 information
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/1_4kzn6p7b/format/url/protocol/http/flavorId/1_lmo6gks3'
[download] Destination: Introduction to the Complete Python Guide-1_4kzn6p7b.mp4
[download] 100% of 17.36MiB in 00:10
[download] Finished downloading playlist: Python – Complete Python, Django, Data Science and ML Guide
```

2024-06-13 16:48 UTC, dirkf commented
I made a version of your PR from yt-dl with yt-dlp (other than conventional) changes back-ported.

With no login, I'm able to get the formats for https://www.oreilly.com/library/view/python-complete/9781835465141, with durations != 1 minute (470 items):
```console
$ python3 -m youtube_dl --get-filename -o  '%(duration)s' 'https://www.oreilly.com/library/view/python-complete/9781835465141'
155
346
311
162
184
323
467
165
288
435
665
729
587
350
487
488
...
```
However, when I get the video it comes as 60s rather than the expected duration.

Presumably with a valid login it takes the `if self.LOGGED_IN:` branch and gets the actual course media.

Please show the actual command that gives the unexpected format. I very much hope that there is some CLI problem that is causing the specified format to be ignored.

2024-06-13 17:29 UTC, dirkf requested changes
I've logged the changes in my version of your code. Then it runs under Py2 and Py3 per yt-dl requirements:
```console
$ python -m youtube_dl -Fv 'https://www.oreilly.com/library/view/python-complete/9781835465141' --playlist-items 1
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-Fv', u'https://www.oreilly.com/library/view/python-complete/9781835465141', u'--playlist-items', u'1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 0eafa09a3
[debug] Python 2.7.18 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial - OpenSSL 1.1.1w  11 Sep 2023 - glibc 2.15
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[safari:course] 9781835465141: Downloading course JSON
[download] Downloading playlist: Python – Complete Python, Django, Data Science and ML Guide
[safari:course] playlist Python – Complete Python, Django, Data Science and ML Guide: Collected 470 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[safari:api] 9781835465141/video1_1: Downloading part JSON
[Kaltura] 9781835465141-video1_1: Downloading webpage
[Kaltura] 1_4kzn6p7b: Downloading video info JSON
[Kaltura] 1_4kzn6p7b: Checking mp4-1829 URL
[Kaltura] 1_4kzn6p7b: Downloading m3u8 information
[info] Available formats for 1_4kzn6p7b:
format code  extension  resolution note
mp4-56       mp4        audio only   56k , isom container, 0fps, ~1.04MiB
hls-58       mp4        audio only   58k , mp4a.40.2
mp4-464      mp4        640x360     464k , isom container, avc1, 30fps, ~8.60MiB
hls-508      mp4        640x360     508k 
mp4-660      mp4        854x480     660k , isom container, avc1, 30fps, ~12.22MiB
hls-713      mp4        854x480     713k 
mp4-827      mp4        960x540     827k , isom container, avc1, 30fps, ~15.32MiB
hls-887      mp4        960x540     887k 
mp4-1272     mp4        1280x720   1272k , isom container, avc1, 30fps, ~23.55MiB
hls-1353     mp4        1280x720   1353k 
mp4-1356     mp4        1280x720   1356k , isom container, avc1, 30fps, ~25.11MiB
mp4-1829     mp4        1920x1080  1829k , m4v container, avc1, 60fps, ~33.85MiB
mp4-2363     mp4        1920x1080  2363k , isom container, avc1, 30fps, ~43.74MiB (best)
[download] Finished downloading playlist: Python – Complete Python, Django, Data Science and ML Guide
$ 
```

2024-06-13 17:29 UTC, dirkf commented on youtube_dl/extractor/safari.py
>          if is_logged(urlh):
I think this should take a URL, not a handle, and `geturl()` should be used. Also, we can match www.learning.oreilly.com, learning.oreilly.com but not fakelearning.oreilly.com:
```suggestion
        def is_logged(url):
            parsed_url = compat_urlparse.urlparse(url)
            return parsed_url.hostname.split('.')[-3:] == ['learning', 'oreilly', 'com'] and (
                parsed_url.path.startswith('/home/')
                or (parsed_url.path == '/member/login/' and not parsed_url.query))

        redirect_url = urlh.geturl()

        if is_logged(redirect_url):
```

2024-06-13 17:29 UTC, dirkf commented on youtube_dl/extractor/safari.py
> +            web_url = f'{web_url.rsplit("/", 1)[0]}/{natural_keys[0]}-{natural_keys[1][:-5]}'
No f-strings in yt-dl:
```suggestion
            web_url = '{0}/{1}-{2}'.format(
                web_url.rsplit('/', 1)[0], natural_keys[0], natural_keys[1][:-5])
```

2024-06-13 17:29 UTC, dirkf commented on youtube_dl/extractor/safari.py
> +            'https://www.oreilly.com/member/login/', None, 'Logging in',
As before.
```suggestion
            self._LOGIN_URL, None, 'Logging in',
```

2024-06-13 17:29 UTC, dirkf commented on youtube_dl/extractor/safari.py
> -
Revert for yt-dl.
```suggestion
# coding: utf-8
from __future__ import unicode_literals

```

2024-06-13 17:29 UTC, dirkf commented on youtube_dl/extractor/safari.py
>  import re
If changes below are applied, this will be redundant.
```suggestion
```

2024-06-13 17:29 UTC, dirkf commented on youtube_dl/extractor/safari.py
> +        redirect_url = urlh.url
Redundant after above change:
```suggestion
```

2024-06-13 17:29 UTC, dirkf commented on youtube_dl/extractor/safari.py
> +            mobj = re.match(self._VALID_URL, urlh.url)
```suggestion
            mobj = self._match_valid_url(urlh.geturl())
```

2024-06-13 17:29 UTC, dirkf commented on youtube_dl/extractor/safari.py
> +        if 'library/view' in web_url:
Maybe:
```suggestion
        if '/library/view' in web_url:
```

2024-06-13 17:29 UTC, dirkf commented on youtube_dl/extractor/safari.py
>          qs = compat_parse_qs(parsed_url.query)
```suggestion
        qs = parse_qs(redirect_url)
```
With this, remove import of `compat_parse_qs` and add import of `parse_qs` from `..utils`.

2024-06-13 19:48 UTC, D357R0Y3R commented
Thank you very much @dirkf for suggesting me changes with your valuable time. BTW I have found something interesting this time.

I have currently tried to patch the changes with this [commit](https://github.com/sulyi/yt-dlp/blob/oreilly-login-fix/yt_dlp/extractor/safari.py) the latest codebase in yt-dlp which can now download the full length video with this commit when --cookies are applied. But when credentials are applied its not working and getting errors. But yotube-dl downloads 1:00 minute video when applied this patch no matter the --cookies are applied or not.

### Using yt-dlp-git
```
[debug] Command-line config: ['--continue', '--ignore-errors', '--retries', 'infinite', '--username', 'PRIVATE', '--password', 'PRIVATE', '--output', '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', 'https://www.oreilly.com/library/view/python-complete/9781835465141', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6]
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.9.4-zen1-1-zen-x86_64-with-glibc2.39 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: certifi-2024.06.02, requests-2.32.3, sqlite3-3.46.0, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1820 extractors
[safari:course] Checking if logged in
[debug] [safari:course] Unable to login: Authentication credentials were not provided.
[safari:course] Logging in
ERROR: [safari:course] 9781835465141: Unable to download JSON metadata: HTTPSConnectionPool(host='www.oreilly.com', port=443): Read timed out. (read timeout=20.0) (caused by TransportError("HTTPSConnectionPool(host='www.oreilly.com', port=443): Read timed out. (read timeout=20.0)"))
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 730, in extract
    self.initialize()
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 636, in initialize
    self._perform_login(username, password)
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/safari.py", line 43, in _perform_login
    auth, urlh = self._download_json_handle(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1092, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 953, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 902, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 708, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1252, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1104, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.oreilly.com', port=443): Read timed out. (read timeout=20.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/networking/_requests.py", line 326, in _send
    requests_res = session.request(
                   ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.oreilly.com', port=443): Read timed out. (read timeout=20.0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 889, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 4140, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/networking/_requests.py", line 350, in _send
    raise TransportError(cause=e) from e
yt_dlp.networking.exceptions.TransportError: HTTPSConnectionPool(host='www.oreilly.com', port=443): Read timed out. (read timeout=20.0)
```

2024-06-13 20:31 UTC, closed without merging

2024-06-13 21:45 UTC, dirkf commented
I see that the https://github.com/sulyi/yt-dlp/blob/oreilly-login-fix/yt_dlp/extractor/safari.py code is using a different set of URLs for auth. Presumably there's some issue about setting cookies if you're getting different behaviour with yt-dl vs yt-dlp